apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: support-sphere-predictive-analytics
  namespace: monitoring
spec:
  groups:
  - name: predictive.metrics
    rules:
    - record: support_sphere:churn_risk:probability
      expr: |
        (
          rate(customer_inactive_days[30d]) * 0.3 +
          rate(negative_feedback_total[30d]) * 0.3 +
          rate(missed_sla_total[30d]) * 0.4
        ) / scalar(count(customer_id))
    - alert: HighChurnRisk
      expr: support_sphere:churn_risk:probability > 0.4
      for: 24h
      labels:
        severity: critical
        team: retention
      annotations:
        summary: High customer churn risk detected
        description: Churn probability at {{ $value }}%

  - name: revenue.metrics
    rules:
    - record: support_sphere:revenue_forecast:trend
      expr: |
        predict_linear(monthly_revenue_total[6m], 31 * 24 * 3600)
    - alert: RevenueTrendNegative
      expr: support_sphere:revenue_forecast:trend < 0
      for: 48h
      labels:
        severity: critical
        team: finance
      annotations:
        summary: Negative revenue trend detected
        description: Projected revenue decline of {{ $value }}%

  - name: ai.optimization
    rules:
    - record: support_sphere:ai_routing_efficiency:score
      expr: |
        sum(rate(correct_ai_routing_total[1h]))
        /
        sum(rate(total_ai_routing_attempts[1h]))
    - alert: AIRoutingDegradation
      expr: support_sphere:ai_routing_efficiency:score < 0.95
      for: 30m
      labels:
        severity: warning
        team: ai-ops
      annotations:
        summary: AI routing efficiency degraded
        description: Routing accuracy at {{ $value }}%

  - name: customer.journey
    rules:
    - record: support_sphere:customer_journey:completion
      expr: |
        sum(rate(successful_journey_steps_total[24h]))
        /
        sum(rate(total_journey_steps[24h]))
    - alert: JourneyCompletionLow
      expr: support_sphere:customer_journey:completion < 0.8
      for: 6h
      labels:
        severity: warning
        team: ux
      annotations:
        summary: Low customer journey completion
        description: Journey completion rate at {{ $value }}%

  - name: support.quality
    rules:
    - record: support_sphere:support_quality:score
      expr: |
        (
          sum(rate(first_contact_resolution_total[24h])) * 0.4 +
          sum(rate(positive_feedback_total[24h])) * 0.3 +
          sum(rate(sla_met_total[24h])) * 0.3
        ) / scalar(count(support_interaction_id))
    - alert: QualityScoreDrop
      expr: support_sphere:support_quality:score < 0.9
      for: 4h
      labels:
        severity: critical
        team: quality
      annotations:
        summary: Support quality score below threshold
        description: Quality score at {{ $value }}

  - name: knowledge.base
    rules:
    - record: support_sphere:kb_effectiveness:score
      expr: |
        sum(rate(successful_kb_resolutions[24h]))
        /
        sum(rate(kb_article_views[24h]))
    - alert: KBEffectivenessLow
      expr: support_sphere:kb_effectiveness:score < 0.6
      for: 24h
      labels:
        severity: warning
        team: content
      annotations:
        summary: Knowledge base effectiveness low
        description: KB resolution rate at {{ $value }}%

  - name: real_time.forecasting
    rules:
    - record: support_sphere:ticket_volume:forecast
      expr: |
        predict_linear(ticket_volume_total[7d], 24 * 3600)
    - alert: UnexpectedTicketSpike
      expr: |
        ticket_volume_total > 
        (support_sphere:ticket_volume:forecast * 1.3)
      for: 1h
      labels:
        severity: warning
        team: operations
      annotations:
        summary: Unexpected ticket volume spike
        description: Volume {{ $value }}% above forecast
