apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
  namespace: support-sphere
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodb-backup
            image: mongo:latest
            command:
            - /bin/sh
            - -c
            - |
              mongodump --uri="${MONGODB_URI}" --archive=/backup/mongodb-$(date +%Y%m%d-%H%M%S).gz --gzip
              aws s3 cp /backup/mongodb-*.gz s3://support-sphere-backups/mongodb/
            env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: support-sphere-secrets
                  key: MONGODB_URI
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-key
            volumeMounts:
            - name: backup
              mountPath: /backup
          volumes:
          - name: backup
            emptyDir: {}
          restartPolicy: OnFailure
