all:
  children:
    kubernetes:
      hosts:
        master:
          ansible_host: "{{ master_ip }}"
        workers:
          hosts:
            worker1:
              ansible_host: "{{ worker1_ip }}"
            worker2:
              ansible_host: "{{ worker2_ip }}"
    monitoring:
      hosts:
        prometheus:
          ansible_host: "{{ prometheus_ip }}"
        grafana:
          ansible_host: "{{ grafana_ip }}"
